# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75bd61f178ae96c0e891385910ba62645141c547935492839d165f424cd653551cd02cc52804f64464d1614ff31fa0458267a73d06a56e364a9e3c59043c5a15
  key_prod: ''
  sec_prod: ''
  key_uat: '8z74RuC3KcThG79CSXMU1vWaqyjABrqLdHNUMMuG0uZsYjJhw2'
  sec_uat: 'J3ddoTDpZDH1H8xWGwkSbnt7IG6O6K8DdBztUyvH4BwVRqJH5Z'

test:
  secret_key_base: 1d74e197e8cd29adceba97050ba2b81a2cbeb01d8b516b0379b0a83b3cc3951cfc00cd36ed9d7327293f7fdc2e18ce38ba5a64af5ba606237be23a9c3cea0a76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  key_prod: <%= ENV["DWKEYPROD"] %>
  sec_prod: <%= ENV["DWSECPROD"] %>
  key_uat: <%= ENV["DWKEYUAT"] %>
  sec_uat: <%= ENV["DWSECUAT"] %>